# Generated by Django 4.1 on 2022-08-10 13:02

from django.db import migrations, models
import django.db.models.deletion
import test_db.create_random
from ..models import Main


def create_instances(apps, schema):
    #Main.create_n()
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='test_db.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Name')),
                ('boolean', models.BooleanField(default=test_db.create_random.create_random_boolean, verbose_name='Boolean')),
                ('char', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Char')),
                ('date', models.DateField(default=test_db.create_random.create_random_date, verbose_name='date')),
                ('datetime', models.DateTimeField(default=test_db.create_random.create_random_datetime, verbose_name='DateTime')),
                ('decimal', models.DecimalField(decimal_places=2, default=test_db.create_random.create_random_decimal, max_digits=4, verbose_name='Decimal')),
                ('duration', models.DurationField(default=test_db.create_random.create_random_duration, verbose_name='Duration')),
                ('email', models.EmailField(default=test_db.create_random.create_random_email, max_length=254, verbose_name='Email')),
                ('float', models.FloatField(default=test_db.create_random.create_random_float, verbose_name='Float')),
                ('ipaddress', models.GenericIPAddressField(default=test_db.create_random.create_random_ipaddress, verbose_name='IP Address')),
                ('integer', models.IntegerField(default=test_db.create_random.create_random_integer, verbose_name='Integer')),
                ('json', models.JSONField(default=test_db.create_random.create_random_json, verbose_name='Json')),
                ('positivebiginteger', models.PositiveBigIntegerField(default=test_db.create_random.create_random_positivebiginteger, verbose_name='PositiveBigInteger')),
                ('positiveinteger', models.PositiveIntegerField(default=test_db.create_random.create_random_positiveinteger, verbose_name='PositiveInteger')),
                ('positivesmallinteger', models.PositiveSmallIntegerField(default=test_db.create_random.create_random_positivesmallinteger, verbose_name='PositiveSmallInteger')),
                ('slug', models.SlugField(default=test_db.create_random.create_random_slug, verbose_name='Slug')),
                ('smallinteger', models.SmallIntegerField(default=test_db.create_random.create_random_smallinteger, verbose_name='SmallInteger')),
                ('text', models.TextField(default=test_db.create_random.create_random_text, verbose_name='Text')),
                ('time', models.TimeField(default=test_db.create_random.create_random_time, verbose_name='Time')),
                ('url', models.URLField(default=test_db.create_random.create_random_url, verbose_name='URL')),
                ('uuid', models.UUIDField(default=test_db.create_random.create_random_uuid, verbose_name='UUID')),
                ('nullable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nullable')),
                ('attributes', models.ManyToManyField(related_name='mains', through='test_db.AttributeValue', to='test_db.attribute', verbose_name='Attributes')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_db.parent')),
                ('tags', models.ManyToManyField(related_name='mains', to='test_db.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Name')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_db.main')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_db.main'),
        ),
        migrations.RunPython(create_instances, migrations.RunPython.noop),
    ]
