# Generated by Django 4.1 on 2023-01-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['id']},
        ),
    ]
