# Generated by Django 4.1 on 2023-01-26 12:52

from django.db import migrations, models
import django.db.models.deletion
import test_db.create_random
import test_db.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0002_alter_main_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['id'], 'verbose_name': 'Main'},
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(default=test_db.create_random.create_random_char, max_length=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='main',
            name='parent',
            field=models.ForeignKey(default=test_db.models.get_random_parent, on_delete=django.db.models.deletion.CASCADE, to='test_db.parent'),
        ),
    ]
