name: Django CI

on: [push, pull_request]

jobs:
  test:
    name: Django-${{ matrix.django-version }}_Python{{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        django-version: ['3.2', '4.2']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install .[test]
        pip install "django~=${{ matrix.django-version }}"
    - name: Run Tests
      run: python tests/manage.py test
